Improved overall user experience with test script
- Featuring a brand new name, Corewarion!
  - It is a clin d'oeil to Criterion, our beloved testing library.

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -4,18 +4,27 @@ success=0
 skipped=0
 failures=0
 
+echo -e "[COREWARION] Initializing...\n"
+
 if [ ! -x "asm/asm" ]; then
     echo "No executable found, please build the project first."
 
-    exit 1
+    read -p "Would you like to build it now? (y/n) " -n 1 -r
+
+    if [ "$REPLY" != "y" ]; then
+        echo -e "\nOk... build it yourself then!"
+        exit 1
+    fi
+
+    make
+
+    echo -e "Project built, getting back on track!\n"
 fi
 
 for champion in champions/src/*.s; do
     name=$(basename "$champion" | cut -d. -f1)
     output="champions/src/$name.cor"
     expected="champions/bin/$name.cor"
-
-    echo -e "Testing champion \e[93m$name\e[39m..."
 
     if [ ! -f "champions/bin/$name.cor" ]; then
         let "skipped=skipped+1"
@@ -27,13 +36,13 @@ for champion in champions/src/*.s; do
     asm/asm "$champion"
 
     if [ $? -ne 0 ]; then
-        let "skipped=skipped+1"
-        echo -e "Failed to compile \e[91m$name\e[39m, skipping test..."
+        let "failures=failures+1"
+        echo -e "failures to compile \e[91m$name\e[39m, more informations above..."
 
         continue
     fi
 
-    echo -e "Compiled \e[95m$name\e[39m."
+    echo -e "Compiling \e[95m$name\e[39m champion..."
 
     diff "$output" "$expected" > /dev/null
 
@@ -48,7 +57,7 @@ for champion in champions/src/*.s; do
     echo -e "The champion \e[92m$name\e[39m has been properly compiled.\n"
 done
 
-echo -e "[COREWAR] Success: \e[92m$success\e[39m | Failures: \e[91m$failures\e[39m | Skipped: \e[37m$skipped\e[39m"
+echo -e "[COREWARION] Success: \e[92m$success\e[39m | Failures: \e[91m$failures\e[39m | Skipped: \e[37m$skipped\e[39m"
 
 if [ $failures -ne 0 ]; then
     exit 1
